name: jdb

on:
  repository_dispatch:
    types: jdb
  workflow_dispatch:
  #schedule:
    #- cron: 00 23 * * *

env:
  UPLOAD_RELEASE: true
  FILE_NAME: jdb

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:    
    - name: Checkout
      uses: actions/checkout@main
    - name: 打包镜像
      uses: unifreq/openwrt_packit@master
      env:
        PACKAGE_SOC: all
        OPENWRT_ARMVIRT: https://github.com/binge8/op/releases/download/jarmv8/openwrt-armvirt-64-default-rootfs.tar.gz
        KERNEL_VERSION_NAME: 5.4.170_5.16.2
    - name: upload release
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        allowUpdates: true
        tag: jarmv8
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
    - name: pushbot推送
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions云编译","content":"${{ env.FILE_NAME }}成功","template":"json"}' http://www.pushplus.plus/send
