name: 打包

on:
  repository_dispatch:
    types: [db]
  workflow_dispatch:
    inputs:
      ssh:
        description: 'bd'
        required: false
        default: 'false'
  schedule:
    - cron: 00 23 * * *

env:
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai
  FILE_NAME: 打包

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:    
    - name: WeChat notification #pushbot推送
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions云编译","content":"${{ env.FILE_NAME }}开始","template":"json"}' http://www.pushplus.plus/send
    - name: Checkout
      uses: actions/checkout@main
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "$TZ"
    - name: Check space usage
      if: (!cancelled())
      run: df -hT
    - name: 打包镜像
      uses: unifreq/openwrt_packit@master
      env:
        PACKAGE_SOC: all
        OPENWRT_ARMVIRT: https://github.com/binge8/op/releases/download/larmv8/openwrt-armvirt-64-default-rootfs.tar.gz
        KERNEL_VERSION_NAME: 5.4.170_5.16.2
    - name: Organize files
      run: |
        cd ${{ env.PACKAGED_OUTPUTPATH }}
        tar -zcvf bin1.tar.gz *
    - name: upload release
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        allowUpdates: true
        tag: larmv8
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
    - name: WeChat notification #pushbot推送
      run: curl -H "Content-Type:application/json" -X POST -d '{"token":"${{ secrets.pushbot }}","title":"Actions云编译","content":"${{ env.FILE_NAME }}成功-结束${{ env.time }}","template":"json"}' http://www.pushplus.plus/send
